### ISSUE TITLE
Indent tag declaration beginnings of embedded structs

### ISSUE THREAD

**Issue by f-person** [segmentio/golines#14]
Here is an example: MyStruct2's tags are not aligned with other fields of MyStruct. It will be nice if tag declaration beginnings were aligned too.

```go
package fixtures

type MyStruct struct {
	Field1    string `json:"field3" tag:"something"`
	Field2    string `              tag:"something else"`
	MyStruct2 `json:"ms2"    tag:"tada"`
}

type MyStruct2 struct {
	Field3 string `json:"field3"`
}
```

**Comment by yolken-segment** [comment]
Hi, thanks for the suggestion. Unfortunately, this isn't easy to do because `gofmt` and `goimports` (which are run as part of the `golines` loop) will enforce that the `string`, `string`, `json:"..." ..."` column is left-aligned. We could do something like this:

```
type MyStruct struct {
	Field1    string `json:"field3" tag:"something"`
	Field2    string `              tag:"something else"`
	MyStruct2 `       json:"ms2"    tag:"tada"`
}
```

but that looks a little weird to me. Open to other suggestions!

**Comment by f-person** [comment]
Nothing else comes to my mind.
I actually like the style you suggested, it's better than the original thing.

**Comment by yolken-segment** [comment]
Ok, let's try to implement that approach. I also noticed that we're not aligning tags in embedded structs, so this can be an opportunity to fix that too.

**Comment by yolken-segment** [comment]
This should be mostly fixed by https://github.com/segmentio/golines/pull/16. Because of the complexity around how nodes are rendered, it's not currently handling 100% of possible cases. However, it should handle the most common ones and fall back gracefully if it can't figure out the right prefix width to use.
